# Kind kubernetes release images https://github.com/kubernetes-sigs/kind/releases
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:{{ .ExposedRegistryPort }}"]
    endpoint = ["http://{{ .RegistryHostname }}:{{ .InternalRegistryPort }}"]
nodes:
- role: control-plane
  image: "kindest/node:{{ .KubernetesVersion }}"
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: memory=4Gi
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 8880
    protocol: TCP
  - containerPort: 443
    hostPort: 8443
    protocol: TCP
  {{ range .ExtraPortsMapping }}- containerPort: {{ .ContainerPort }}
    hostPort: {{ .HostPort }}
    protocol: TCP{{ end }}